default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: superails_development

test:
  <<: *default
  database: superails_test

production:
  <<: *default
  database: superails_production
  username: superails
  password: <%= ENV['superails_DATABASE_PASSWORD'] %>
